(component
  (type (;0;)
    (instance
      (export (;0;) "incoming-body" (type (sub resource)))
      (type (;1;) (own 0))
      (type (;2;) (record (field "body" 1)))
      (export (;3;) "request" (type (eq 2)))
    )
  )
  (import "test:resource-record/http" (instance (;0;) (type 0)))
  (alias export 0 "incoming-body" (type (;1;)))
  (type (;2;) (own 1))
  (type (;3;) (record (field "body" 2)))
  (import "request" (type (;4;) (eq 3)))
  (type (;5;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (func))
          (export (;0;) "ping" (func (type 0)))
        )
      )
      (export (;0;) "test:resource-record/bridge" (instance (type 0)))
    )
  )
  (import "unlocked-dep=<test:plug>" (component (;0;) (type 5)))
  (instance (;1;) (instantiate 0))
  (alias export 1 "test:resource-record/bridge" (instance (;2;)))
  (type (;6;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "incoming-body" (type (sub resource)))
          (type (;1;) (own 0))
          (type (;2;) (record (field "body" 1)))
          (export (;3;) "request" (type (eq 2)))
        )
      )
      (import "test:resource-record/http" (instance (;0;) (type 0)))
      (type (;1;)
        (instance
          (type (;0;) (func))
          (export (;0;) "ping" (func (type 0)))
        )
      )
      (import "test:resource-record/bridge" (instance (;1;) (type 1)))
      (alias export 0 "incoming-body" (type (;2;)))
      (type (;3;) (own 2))
      (type (;4;) (record (field "body" 3)))
      (import "request" (type (;5;) (eq 4)))
      (type (;6;) (func (param "req" 5)))
      (export (;0;) "handle" (func (type 6)))
    )
  )
  (import "unlocked-dep=<test:socket>" (component (;1;) (type 6)))
  (instance (;3;) (instantiate 1
      (with "test:resource-record/bridge" (instance 2))
      (with "test:resource-record/http" (instance 0))
      (with "request" (type 4))
    )
  )
  (alias export 3 "handle" (func (;0;)))
  (export (;1;) "handle" (func 0))
)
